title: James Truitt
description: Long Form Jekyll theme built with SASS

url: jamestruitt.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about

social:
    github: jtruitt1
    linkedin: james-truitt-786193b8
    bsky: linguistory.bsky.social
    mastodon: linguistory@code4lib.social

